In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.7.0'

In [2]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
import keras 
from keras.models import Sequential
from keras.layers import Dense

In [12]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer…

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second hidden layer…

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer…

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Compiling the ANN…

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Fitting the ANN to the Training set


In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7686
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4852 - accuracy: 0.7946
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4608 - accuracy: 0.7940
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4434 - accuracy: 0.7976
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4314 - accuracy: 0.8018
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4235 - accuracy: 0.8052
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4167 - accuracy: 0.8096
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4093 - accuracy: 0.8140
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3994 - accuracy: 0.8202
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3902 - accura

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Making the predictions and evaluating the model

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1526   69]
 [ 205  200]]
